name: Run e2e tests & tests for the multi-tool-package
on:
  push:
    branches:
      - '**'

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '8.11'          
      - name: Start Application
        run: |
          yarn
          yarn start &
          
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install multi-tool-package modules
        working-directory: src/test/multi-tool-package
        run: npm install 
            
      - name: Install e2e test suite modules
        working-directory: src/test/e2e
        run: npm install 

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Run e2e tests
        working-directory: src/test/e2e
        run: npm test
  multi-tool-package-tests:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Run multi-tool-package tests
        working-directory: src/test/multi-tool-package
        run: npm test